### ISSUE TITLE
Branch select component doesn't return to default value on repo change

### ISSUE THREAD

**Issue by aralsto** [jonahnewman/zr-git-webext#13]
**Describe the bug**
The branch select drop-down displays the previous branch selected after the repo has been changed.

**To Reproduce**
1. Select repo A
2. Select some branch in repo A
3. Change to repo B
4. See bug: select component still has the last selected branch highlighted

**Expected behavior**
The select component should go back to displaying its default value.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome

**Additional context**
Possibly have to switch to react forms or figure out some other way to have the component display null selection.

**Comment by averynewman** [comment]
Commit 0340c1677e0368139fa8adfed6b28e898b7ccb75 resolves this issue by re-rendering the react-select dropdown with its new default value each time the repository is changed.
