### ISSUE TITLE
Enable github interface for simulation opponents

### ISSUE THREAD

**Issue by averynewman** [jonahnewman/zr-git-webext#20]
**Is your feature request related to a problem? Please describe.**
It is often desirable to simulate two different versions of code against each other in the ZR competition. The website's interface for simulating allows the user to select opponents from its own cloud files. To simulate two different versions stored on a Git server against each other, the user would have to open a new document on the ZR website, fetch one version, open another document, fetch the other version, then simulate one against the other. This is a rather unwieldy operation.

**Describe the solution you'd like**
I would like to inject a script that adds an option to the simulation popup allowing the user to select any of the branches from the currently selected repository as an opponent for the simulation.

**Additional context**
The original zr-github-crx extension did this. We may be able to adapt the content script it used for the same purpose.

**Comment by aralsto** [comment]
Added in commit a0b5339.
